replicaCount: 1

image:
  repository: ghcr.io/toeverything/affine-front
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: "affine-web"

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: affine.pro
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: '500m'
    memory: 2Gi
  requests:
    cpu: '500m'
    memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
